# -*- coding: utf-8 -*-
"""Double Correlation Method - M. Rafiudin Abas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWjTbXzl1dxU5knXql1yF0IE2pUEDUls
"""

# ==============================================================================
# SETUP: LIBRARY & KONEKSI GOOGLE DRIVE
# ==============================================================================
!pip install cartopy
import cartopy

import os
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
from matplotlib.colors import ListedColormap, TwoSlopeNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from scipy.stats import pearsonr
import warnings
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/content/drive')


# ==============================================================================
# TAHAP 0: MEMUAT DATA CURAH HUJAN
# ==============================================================================

FILE_PATH = "/content/drive/MyDrive/DataTA/SumatBag-Selatan_1983-2024.nc"   # <-- Sesuaikan nama file jika berbeda

# -*- coding: utf-8 -*-
"""Double Correlation Method

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXv05wMGyWSxg-f5c8mCO9lpZ8qcUFyG
"""


ds = xr.open_dataset(FILE_PATH)
print(ds)

VAR_NAME = "precip"   # <-- Ganti jika nama variabel berbeda di file Anda

rain = ds[VAR_NAME]   # shape: (time, lat, lon)
lats = ds["latitude"].values if "latitude" in ds else ds["lat"].values
lons = ds["longitude"].values if "longitude" in ds else ds["lon"].values
times = ds["time"].values

print(f"\n✅ Data dimuat: {rain.shape} | Periode: {str(times[0])[:10]} s.d. {str(times[-1])[:10]}")
print(f"   Lat: {lats.min():.2f}°–{lats.max():.2f}° | Lon: {lons.min():.2f}°–{lons.max():.2f}°")


# ==============================================================================
# TAHAP 1: KLIMATOLOGI BULANAN PER GRID
# ==============================================================================

print("\n--- [TAHAP 1] Menghitung Klimatologi Bulanan per Grid ---")

# Rata-ratakan data per bulan (groupby month) untuk mendapat siklus tahunan
# klimatologis (12 nilai Jan-Des) pada setiap titik grid, lalu simpan ke NetCDF.
rain_clim = rain.groupby("time.month").mean(dim="time")   # shape: (12, lat, lon)

out_clim_path = "/content/chirps_klimatologi_bulanan.nc"
rain_clim.to_netcdf(out_clim_path)

print(f"✅ Klimatologi bulanan (12 bulan × {len(lats)} lat × {len(lons)} lon) dihitung.")
print(f"   File disimpan: {out_clim_path}")

clim = rain_clim.values          # array numpy (12, nlat, nlon) untuk komputasi selanjutnya
nlat, nlon = len(lats), len(lons)


# ==============================================================================
# TAHAP 2: PENENTUAN DUA TITIK REFERENSI
# ==============================================================================
# Ref-1: wilayah lebih selatan (~4°-5° LS) | Ref-2: mendekati ekuator (~1.5°-2° LS)

REF1_LAT, REF1_LON = -5.3, 105.3    # <-- Ganti sesuai pilihan Anda
REF2_LAT, REF2_LON = -1.6, 100.6    # <-- Ganti sesuai pilihan Anda

lat1, lon1 = -5.1, 105.1
lat2, lon2 = -2.2, 101

def find_nearest_idx(arr, val):
    """Temukan indeks nilai terdekat dalam array."""
    return int(np.argmin(np.abs(arr - val)))

# Cari indeks grid terdekat dari kedua titik referensi, lalu ambil siklus
# tahunan klimatologisnya (12 nilai) sebagai acuan korelasi.
ref1_i = find_nearest_idx(lats, REF1_LAT)
ref1_j = find_nearest_idx(lons, REF1_LON)
ref2_i = find_nearest_idx(lats, REF2_LAT)
ref2_j = find_nearest_idx(lons, REF2_LON)

clim_ref1 = clim[:, ref1_i, ref1_j]   # siklus tahunan Ref-1
clim_ref2 = clim[:, ref2_i, ref2_j]   # siklus tahunan Ref-2

print(f"  Ref-1 → Lat: {lats[ref1_i]:.2f}°, Lon: {lons[ref1_j]:.2f}°")
print(f"  Ref-2 → Lat: {lats[ref2_i]:.2f}°, Lon: {lons[ref2_j]:.2f}°")

bulan_label = ["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"]

# PLOT REFERENSI: SIKLUS TAHUNAN DUA TITIK REFERENSI
fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(range(1,13), clim_ref1, "o-", color="steelblue", linewidth=2, label=f"Ref-1 ({lats[ref1_i]:.2f}°LS, {lons[ref1_j]:.2f}°BT)")
ax.plot(range(1,13), clim_ref2, "s-", color="tomato",    linewidth=2, label=f"Ref-2 ({lats[ref2_i]:.2f}°LS, {lons[ref2_j]:.2f}°BT)")
ax.set_xticks(range(1,13)); ax.set_xticklabels(bulan_label)
ax.set_xlabel("Bulan"); ax.set_ylabel("Curah Hujan (mm/bulan)")
ax.set_title("Siklus Tahunan Klimatologis – Dua Titik Referensi", fontweight="bold")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); plt.savefig("/content/ref_siklus_tahunan.png", dpi=150)
plt.show()
print("✅ Plot siklus tahunan referensi selesai.")


# ==============================================================================
# TAHAP 3: KORELASI PERTAMA - SETIAP GRID VS. TITIK REFERENSI
# ==============================================================================
# Keluaran: peta spasial koefisien korelasi (r) tiap grid terhadap Ref-1/Ref-2

print("\n--- [TAHAP 3] Korelasi Pertama: Setiap Grid vs. Referensi ---")

R_THRESHOLD_R = 0.823   # ambang batas r sesuai Aldrian & Susanto (99% CI)

def pearson_map(clim_arr, clim_ref):
    """
    Hitung korelasi Pearson antara siklus tahunan setiap grid (12 nilai)
    dengan siklus tahunan titik referensi.
    Mengembalikan array 2D (nlat x nlon) berisi nilai r.
    """
    nlat_, nlon_ = clim_arr.shape[1], clim_arr.shape[2]
    r_map = np.full((nlat_, nlon_), np.nan)
    ref_anom = clim_ref - clim_ref.mean()
    denom_ref = np.sqrt((ref_anom**2).sum())

    for i in range(nlat_):
        for j in range(nlon_):
            grid_ts = clim_arr[:, i, j]
            if np.isnan(grid_ts).any():
                continue
            grid_anom = grid_ts - grid_ts.mean()
            denom_grid = np.sqrt((grid_anom**2).sum())
            if denom_grid == 0 or denom_ref == 0:
                continue
            r_map[i, j] = (grid_anom * ref_anom).sum() / (denom_grid * denom_ref)
    return r_map

r1_map = pearson_map(clim, clim_ref1)
r2_map = pearson_map(clim, clim_ref2)

mask1_k1 = (r1_map >= R_THRESHOLD_R)
mask2_k1 = (r2_map >= R_THRESHOLD_R)

print(f"  Korelasi Ref-1 selesai | r ≥ 0.823: {mask1_k1.sum()} grid")
print(f"  Korelasi Ref-2 selesai | r ≥ 0.823: {mask2_k1.sum()} grid")


# ==============================================================================
# KONFIGURASI TAMPILAN PETA (dipakai oleh seluruh plot spasial di bawah)
# ==============================================================================

plt.rcParams.update({
    'font.family'     : 'serif',
    'font.size'       : 12,
    'axes.titlesize'  : 12,
    'axes.labelsize'  : 11,
    'xtick.labelsize' : 11,
    'ytick.labelsize' : 11,
    'figure.dpi'      : 120,
    'savefig.dpi'     : 150,
    'savefig.bbox'    : 'tight',
})

LON_MIN, LON_MAX = 100.5, 108.5
LAT_MIN, LAT_MAX = -6.0, -1.5
BULAN_LABEL = bulan_label

def _map_extent_and_decor(ax, extent=None):
    """Terapkan extent, garis pantai, batas negara, dan gridlines standar ke peta."""
    if extent is None:
        extent = [LON_MIN, LON_MAX, LAT_MIN, LAT_MAX]
    ax.set_extent(extent, crs=ccrs.PlateCarree())
    ax.coastlines(resolution='10m', linewidth=0.7)
    ax.add_feature(cfeature.BORDERS, linewidth=0.4, linestyle=':')
    gl = ax.gridlines(draw_labels=True, linewidth=0.3, color='gray', alpha=0.6,
                      x_inline=False, y_inline=False)
    gl.top_labels = gl.right_labels = False
    gl.xlocator = mticker.MultipleLocator(2)
    gl.ylocator = mticker.MultipleLocator(1)

# Folder output di Google Drive untuk seluruh figur bernomor
OUTPUT_DIR = '/content/drive/MyDrive/DataTA/DCM3/1/'
os.makedirs(OUTPUT_DIR, exist_ok=True)

lons2d, lats2d = np.meshgrid(lons, lats)


# ==============================================================================
# PLOT 1: PETA KORELASI PERTAMA - REF-1
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

pcm = ax.pcolormesh(lons2d, lats2d, r1_map,
                    vmin=-1, vmax=1, cmap='RdBu_r',
                    transform=ccrs.PlateCarree(),
                    shading='nearest')
_map_extent_and_decor(ax)
ax.plot(lons[ref1_j], lats[ref1_i], '*', markersize=14, color='lime',
        transform=ccrs.PlateCarree())

# Label (a) pojok kiri bawah + keterangan pojok kanan bawah
ax.text(0.02, 0.04, '(a)', transform=ax.transAxes,
        fontsize=14, fontweight='bold', va='bottom', ha='left',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))
ax.text(0.98, 0.04,
        f'Korelasi Pertama: Ref-1\n({lats[ref1_i]:.1f}°LS, {lons[ref1_j]:.1f}°BT)',
        transform=ax.transAxes,
        fontsize=10, fontweight='bold', va='bottom', ha='right',
        multialignment='right',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))

cbar = plt.colorbar(pcm, ax=ax, orientation='horizontal', pad=0.04, shrink=0.85)
cbar.set_label('Koefisien Korelasi (r)', fontsize=11)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}01_peta_korelasi_pertama_ref1.png')
plt.show()
print(f"✅ Plot 1: {OUTPUT_DIR}01_peta_korelasi_pertama_ref1.png")


# ==============================================================================
# PLOT 2: PETA KORELASI PERTAMA - REF-2
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

pcm = ax.pcolormesh(lons2d, lats2d, r2_map,
                    vmin=-1, vmax=1, cmap='RdBu_r',
                    transform=ccrs.PlateCarree(),
                    shading='nearest')
_map_extent_and_decor(ax)
ax.plot(lons[ref2_j], lats[ref2_i], '*', markersize=14, color='lime',
        transform=ccrs.PlateCarree())

ax.text(0.02, 0.04, '(b)', transform=ax.transAxes,
        fontsize=14, fontweight='bold', va='bottom', ha='left',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))
ax.text(0.98, 0.04,
        f'Korelasi Pertama: Ref-2\n({lats[ref2_i]:.1f}°LS, {lons[ref2_j]:.1f}°BT)',
        transform=ax.transAxes,
        fontsize=10, fontweight='bold', va='bottom', ha='right',
        multialignment='right',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))

cbar = plt.colorbar(pcm, ax=ax, orientation='horizontal', pad=0.04, shrink=0.85)
cbar.set_label('Koefisien Korelasi (r)', fontsize=11)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}02_peta_korelasi_pertama_ref2.png')
plt.show()
print(f"✅ Plot 2: {OUTPUT_DIR}02_peta_korelasi_pertama_ref2.png")


# ==============================================================================
# PLOT 3: GRID TERPILIH KORELASI PERTAMA - REF-1
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

pcm = ax.pcolormesh(lons2d, lats2d, mask1_k1.astype(float),
                    vmin=0, vmax=1, cmap='Blues',
                    transform=ccrs.PlateCarree(),
                    shading='nearest', alpha=0.7)
_map_extent_and_decor(ax)
ax.plot(lons[ref1_j], lats[ref1_i], 'r*', markersize=14,
        transform=ccrs.PlateCarree())

ax.text(0.02, 0.04, '(a)', transform=ax.transAxes,
        fontsize=14, fontweight='bold', va='bottom', ha='left',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))
ax.text(0.98, 0.04,
        f'Grid Terpilih – Ref-1\n(r ≥ 0.823, {mask1_k1.sum()} grid)',
        transform=ax.transAxes,
        fontsize=10, fontweight='bold', va='bottom', ha='right',
        multialignment='right',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}03_grid_terpilih_ref1.png')
plt.show()
print(f"✅ Plot 3: {OUTPUT_DIR}03_grid_terpilih_ref1.png")


# ==============================================================================
# PLOT 4: GRID TERPILIH KORELASI PERTAMA - REF-2
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

pcm = ax.pcolormesh(lons2d, lats2d, mask2_k1.astype(float),
                    vmin=0, vmax=1, cmap='Blues',
                    transform=ccrs.PlateCarree(),
                    shading='nearest', alpha=0.7)
_map_extent_and_decor(ax)
ax.plot(lons[ref2_j], lats[ref2_i], 'r*', markersize=14,
        transform=ccrs.PlateCarree())

ax.text(0.02, 0.04, '(b)', transform=ax.transAxes,
        fontsize=14, fontweight='bold', va='bottom', ha='left',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))
ax.text(0.98, 0.04,
        f'Grid Terpilih – Ref-2\n(r ≥ 0.823, {mask2_k1.sum()} grid)',
        transform=ax.transAxes,
        fontsize=10, fontweight='bold', va='bottom', ha='right',
        multialignment='right',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}04_grid_terpilih_ref2.png')
plt.show()
print(f"✅ Plot 4: {OUTPUT_DIR}04_grid_terpilih_ref2.png")


# ==============================================================================
# TAHAP 4: RATA-RATA SIKLUS TAHUNAN WILAYAH (Persamaan 3.3)
# ==============================================================================

print("\n--- [TAHAP 4] Rata-Rata Siklus Tahunan Wilayah (3.3.1.4) ---")

def regional_annual_cycle(clim_arr, mask):
    """Rata-rata klimatologi bulanan seluruh grid yang lolos seleksi (Pers. 3.3)."""
    K = mask.sum()
    clim_region = np.nanmean(clim_arr[:, mask], axis=1)  # (12,)
    return clim_region, K

clim_region1, K1 = regional_annual_cycle(clim, mask1_k1)
clim_region2, K2 = regional_annual_cycle(clim, mask2_k1)

print(f"  Wilayah Ref-1: K = {K1} grid | Wilayah Ref-2: K = {K2} grid")


# ==============================================================================
# PLOT 5: SIKLUS TAHUNAN WILAYAH (KORELASI PERTAMA)
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 5))

ax.plot(range(1,13), clim_region1, 'o-', color='steelblue', linewidth=2.2,
       markersize=7, label=f'Ref-1 (K={K1})')
ax.plot(range(1,13), clim_region2, 's-', color='tomato', linewidth=2.2,
       markersize=7, label=f'Ref-2 (K={K2})')

ax.set_xticks(range(1,13))
ax.set_xticklabels(BULAN_LABEL)
ax.set_xlabel('Bulan', fontsize=11)
ax.set_ylabel('Curah Hujan (mm/bulan)', fontsize=11)
ax.set_title('Siklus Tahunan Wilayah – Hasil Korelasi Pertama', fontweight='bold', fontsize=12)
ax.legend(fontsize=10)
ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}05_siklus_tahunan_wilayah.png')
plt.show()
print(f"✅ Plot 5: {OUTPUT_DIR}05_siklus_tahunan_wilayah.png")


# ==============================================================================
# TAHAP 5: KORELASI KEDUA - PENETAPAN BATAS WILAYAH FINAL (Persamaan 3.4)
# ==============================================================================

print("\n--- [TAHAP 5] Korelasi Kedua – Penetapan Batas Wilayah Final (3.3.1.5) ---")

# (1) Hitung korelasi-2 untuk Ref-1
r1_map_k2 = pearson_map(clim, clim_region1)
mask1_k2 = (r1_map_k2 >= R_THRESHOLD_R)

# (2) Grid yang sudah masuk wilayah Ref-1 (lolos korelasi-2 Ref-1) TIDAK
#     diikutsertakan dalam perhitungan korelasi-2 untuk Ref-2 (non-overlap)
eligible_for_ref2 = ~mask1_k2

r2_map_k2 = np.full_like(r1_map_k2, np.nan, dtype=float)
_r2_tmp = pearson_map(clim, clim_region2)
r2_map_k2[eligible_for_ref2] = _r2_tmp[eligible_for_ref2]

mask2_k2 = (r2_map_k2 >= R_THRESHOLD_R) & eligible_for_ref2

print(f"  Korelasi-2 Ref-1: r≥0.823 → {mask1_k2.sum()} grid")
print(f"  Korelasi-2 Ref-2: r≥0.823 → {mask2_k2.sum()} grid (non-overlap)")


# ==============================================================================
# PLOT 6: PETA KORELASI KEDUA - REF-1
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

pcm = ax.pcolormesh(lons2d, lats2d, r1_map_k2,
                    vmin=-1, vmax=1, cmap='RdBu_r',
                    transform=ccrs.PlateCarree(),
                    shading='nearest')
_map_extent_and_decor(ax)
ax.plot(lons[ref1_j], lats[ref1_i], 'k*', markersize=14,
        transform=ccrs.PlateCarree())

ax.text(0.02, 0.04, '(a)', transform=ax.transAxes,
        fontsize=14, fontweight='bold', va='bottom', ha='left',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))
ax.text(0.98, 0.04,
        'Korelasi Kedua:\nvs. Siklus Wilayah Ref-1',
        transform=ax.transAxes,
        fontsize=10, fontweight='bold', va='bottom', ha='right',
        multialignment='right',
        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=2))

cbar = plt.colorbar(pcm, ax=ax, orientation='horizontal', pad=0.04, shrink=0.85)
cbar.set_label('Koefisien Korelasi (r)', fontsize=11)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}06_peta_korelasi_kedua_ref1.png')
plt.show()
print(f"✅ Plot 6: {OUTPUT_DIR}06_peta_korelasi_kedua_ref1.png")


# ==============================================================================
# PLOT 7: PETA KORELASI KEDUA - REF-2
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

pcm = ax.pcolormesh(lons2d, lats2d, r2_map_k2,
                    vmin=-1, vmax=1, cmap='RdBu_r',
                    transform=ccrs.PlateCarree(),
                    shading='nearest')
_map_extent_and_decor(ax)
ax.plot(lons[ref2_j], lats[ref2_i], '*', markersize=14, color='lime',
        transform=ccrs.PlateCarree())
ax.set_title('Korelasi Kedua: vs. Siklus Wilayah Ref-2', fontweight='bold', fontsize=12)

cbar = plt.colorbar(pcm, ax=ax, orientation='horizontal', pad=0.04, shrink=0.85)
cbar.set_label('Koefisien Korelasi (r)', fontsize=11)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}07_peta_korelasi_kedua_ref2.png')
plt.show()
print(f"✅ Plot 7: {OUTPUT_DIR}07_peta_korelasi_kedua_ref2.png")


# ==============================================================================
# PLOT 8: WILAYAH FINAL (REF-1 + REF-2 GABUNGAN)
# ==============================================================================
# Warna & style dapat disesuaikan di sini
COLOR_REF1, COLOR_REF2 = 'limegreen', 'royalblue'     # warna wilayah Ref-1 / Ref-2
STAR_REF1,  STAR_REF2  = 'red', 'gold'                # warna bintang Ref-1 / Ref-2

fig, ax = plt.subplots(figsize=(10, 6), subplot_kw={'projection': ccrs.PlateCarree()})

# Overlay dua wilayah (Ref-1 & Ref-2) dengan warna berbeda; area di luar mask
# ditutupi (masked) agar tidak menimpa warna wilayah lainnya.
mask1_plot = np.ma.masked_where(~mask1_k2, mask1_k2)
ax.pcolormesh(lons2d, lats2d, mask1_plot, cmap=ListedColormap([COLOR_REF1]),
              transform=ccrs.PlateCarree(), shading='nearest', alpha=0.8)

mask2_plot = np.ma.masked_where(~mask2_k2, mask2_k2)
ax.pcolormesh(lons2d, lats2d, mask2_plot, cmap=ListedColormap([COLOR_REF2]),
              transform=ccrs.PlateCarree(), shading='nearest', alpha=0.8)

_map_extent_and_decor(ax)

# Titik referensi
ax.plot(lons[ref1_j], lats[ref1_i], marker='*', color=STAR_REF1, markersize=14,
        transform=ccrs.PlateCarree())
ax.plot(lons[ref2_j], lats[ref2_i], marker='*', color=STAR_REF2, markersize=14,
        transform=ccrs.PlateCarree())

# Legenda titik referensi (kanan atas)
star_ref1 = mlines.Line2D([], [], color=STAR_REF1, marker='*', linestyle='None', markersize=12, label='Ref-1')
star_ref2 = mlines.Line2D([], [], color=STAR_REF2, marker='*', linestyle='None', markersize=12, label='Ref-2')
legend1 = ax.legend(handles=[star_ref1, star_ref2], loc='upper right', fontsize=10, framealpha=0.85)
ax.add_artist(legend1)

# Legenda warna wilayah (kiri bawah)
patch_ref1 = mpatches.Patch(color=COLOR_REF1, label='Wilayah Ref-1')
patch_ref2 = mpatches.Patch(color=COLOR_REF2, label='Wilayah Ref-2')
ax.legend(handles=[patch_ref1, patch_ref2], loc='lower left', fontsize=10, framealpha=0.85)

# Keterangan ringkasan jumlah grid (kanan bawah)
ax.text(0.98, 0.04,
        f'Wilayah Final:\nRef-1 (r ≥ 0.823, {mask1_k2.sum()} grid)\nRef-2 (r ≥ 0.823, {mask2_k2.sum()} grid)',
        transform=ax.transAxes,
        fontsize=10, fontweight='bold', va='bottom', ha='right',
        multialignment='right',
        bbox=dict(facecolor='white', alpha=0.70, edgecolor='none', pad=2))

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}08_wilayah_final_ref1_ref2.png')
plt.show()
print(f"✅ Plot 8: {OUTPUT_DIR}08_wilayah_final_ref1_ref2.png")


# ==============================================================================
# TAHAP 6: ANALISIS HASIL DCM (3.3.1.6)
# ==============================================================================
# (a) Siklus tahunan rata-rata wilayah final
# (b) Simpangan baku antartahunan (Persamaan 3.5)

print("\n--- [TAHAP 6] Analisis Hasil DCM (3.3.1.6) ---")

clim_final1, Kf1 = regional_annual_cycle(clim, mask1_k2)
clim_final2, Kf2 = regional_annual_cycle(clim, mask2_k2)

# Simpangan baku antartahunan per bulan per grid (Persamaan 3.5), dihitung dari
# data time series mentah yang dikelompokkan per bulan.
rain_np = rain.values                   # (ntime, nlat, nlon)
months_np = rain["time.month"].values   # array integer bulan (1-12)

std_map = np.full((12, nlat, nlon), np.nan)
for m in range(1, 13):
    idx_m = np.where(months_np == m)[0]
    data_m = rain_np[idx_m]             # (nyears, nlat, nlon)
    clim_m = clim[m-1]                  # (nlat, nlon)
    std_map[m-1] = np.sqrt(((data_m - clim_m[np.newaxis])**2).sum(axis=0) / (len(idx_m) - 1))

std_region1 = np.nanmean(std_map[:, mask1_k2], axis=1)
std_region2 = np.nanmean(std_map[:, mask2_k2], axis=1)

print("  Simpangan baku wilayah final dihitung untuk 12 bulan.")


# ==============================================================================
# PLOT 9: SIKLUS TAHUNAN + STD WILAYAH FINAL REF-1
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 5))

ax.fill_between(range(1,13), clim_final1 - std_region1, clim_final1 + std_region1,
                color='steelblue', alpha=0.2, label='±1 SD antartahunan')
ax.plot(range(1,13), clim_final1, 'o-', color='steelblue', linewidth=2.2,
       markersize=7, label=f'Wilayah Final Ref-1 (K={Kf1})')

ax.set_xticks(range(1,13)); ax.set_xticklabels(BULAN_LABEL)
ax.set_xlabel('Bulan', fontsize=11); ax.set_ylabel('Curah Hujan (mm/bulan)', fontsize=11)
ax.set_title('Siklus Tahunan & Simpangan Baku Antartahunan – Wilayah Final Ref-1',
            fontweight='bold', fontsize=12)
ax.legend(fontsize=10); ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}09_siklus_std_ref1.png')
plt.show()
print(f"✅ Plot 9: {OUTPUT_DIR}09_siklus_std_ref1.png")


# ==============================================================================
# PLOT 10: SIKLUS TAHUNAN + STD WILAYAH FINAL REF-2
# ==============================================================================

fig, ax = plt.subplots(figsize=(10, 5))

ax.fill_between(range(1,13), clim_final2 - std_region2, clim_final2 + std_region2,
                color='tomato', alpha=0.2, label='±1 SD antartahunan')
ax.plot(range(1,13), clim_final2, 's-', color='tomato', linewidth=2.2,
       markersize=7, label=f'Wilayah Final Ref-2 (K={Kf2})')

ax.set_xticks(range(1,13)); ax.set_xticklabels(BULAN_LABEL)
ax.set_xlabel('Bulan', fontsize=11); ax.set_ylabel('Curah Hujan (mm/bulan)', fontsize=11)
ax.set_title('Siklus Tahunan & Simpangan Baku Antartahunan – Wilayah Final Ref-2',
            fontweight='bold', fontsize=12)
ax.legend(fontsize=10); ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}10_siklus_std_ref2.png')
plt.show()
print(f"✅ Plot 10: {OUTPUT_DIR}10_siklus_std_ref2.png")


# ==============================================================================
# PLOT 11: PERBANDINGAN PETA KORELASI KEDUA - DUA REFERENSI
# ==============================================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 5), subplot_kw={"projection": ccrs.PlateCarree()})

# Loop menggambar peta korelasi-2 tiap referensi berikut kontur ambang batas r
for ax, r_map, ref_lat, ref_lon, ttl in [
    (axes[0], r1_map_k2, lats[ref1_i], lons[ref1_j], "Korelasi-2 – Ref-1 (mendekati ekuator)"),
    (axes[1], r2_map_k2, lats[ref2_i], lons[ref2_j], "Korelasi-2 – Ref-2 (lebih selatan)")
]:
    pcm = ax.pcolormesh(lons2d, lats2d, r_map, vmin=-1, vmax=1, cmap="RdBu_r",
                        transform=ccrs.PlateCarree())
    ax.contour(lons2d, lats2d, r_map, levels=[R_THRESHOLD_R], colors="black",
               linewidths=1.2, transform=ccrs.PlateCarree())
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)
    ax.plot(ref_lon, ref_lat, "k*", markersize=12, transform=ccrs.PlateCarree())
    ax.set_title(ttl, fontweight="bold", fontsize=10)
    plt.colorbar(pcm, ax=ax, orientation="horizontal", pad=0.04, label="r (korelasi-2)")

plt.suptitle("Perbandingan Peta Korelasi Kedua – Dua Titik Referensi (3.3.1.6)",
             fontweight="bold", fontsize=12, y=1.01)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}11_perbandingan_korelasi_kedua.png')
plt.show()
print(f"✅ Plot 11: {OUTPUT_DIR}11_perbandingan_korelasi_kedua.png")


# ==============================================================================
# RINGKASAN HASIL DCM
# ==============================================================================

print("\n" + "="*60)
print("  RINGKASAN HASIL DCM")
print("="*60)
print(f"  Ref-1  ({lats[ref1_i]:.2f}°LS, {lons[ref1_j]:.2f}°BT)")
print(f"    Grid lolos korelasi-1 : {mask1_k1.sum()}")
print(f"    Grid lolos korelasi-2 : {mask1_k2.sum()}")
print(f"  Ref-2  ({lats[ref2_i]:.2f}°LS, {lons[ref2_j]:.2f}°BT)")
print(f"    Grid lolos korelasi-1 : {mask2_k1.sum()}")
print(f"    Grid lolos korelasi-2 : {mask2_k2.sum()}")
print("="*60)
print(f"✅ Seluruh tahap DCM selesai. File output tersimpan di {OUTPUT_DIR}")