# -*- coding: utf-8 -*-
"""Seasonal-reliant Empirical Orthogonal Function - M. Rafiudin Abas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5A7sP2Gf8E8FFXDzot-VIOd5j0Igiu2
"""

# ==============================================================================
# SETUP: LIBRARY
# ==============================================================================

!pip install -q cartopy
!pip install -q --no-binary shapely shapely --force
!pip install --upgrade numpy scipy scikit-learn

pip install --upgrade --force-reinstall numpy

import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import matplotlib.dates as mdates
import matplotlib.patches as mpatches
from matplotlib.colors import TwoSlopeNorm
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from sklearn.decomposition import PCA
from scipy import stats
import warnings

# -*- coding: utf-8 -*-
"""Seasonal-reliant Empirical Orthogonal Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7xYvaeQcqSljMtLsu4vlKsK4DiyvDCk
"""


# ==============================================================================
# KONFIGURASI GLOBAL: GAYA VISUAL, KONSTANTA DOMAIN, & PATH DATA
# ==============================================================================

plt.rcParams.update({
    'font.family'     : 'serif',
    'font.size'       : 12,
    'axes.titlesize'  : 14,
    'axes.labelsize'  : 13,
    'xtick.labelsize' : 12,
    'ytick.labelsize' : 12,
    'figure.dpi'      : 120,
    'savefig.dpi'     : 150,
    'savefig.bbox'    : 'tight',
})

LON_MIN, LON_MAX = 100.5, 108.5
LAT_MIN, LAT_MAX = -6.0, -1.5
SEASONS   = ['JJA', 'SON', 'DJF', 'MAM']
N_MODES   = 10          # jumlah mode yang diekstrak
LEAD_MODES = [1, 2]     # mode utama yang dianalisis (Hou et al., 2016)
SEASON_MONTHS = {
    'JJA' : [6, 7, 8],
    'SON' : [9, 10, 11],
    'DJF' : [12, 1, 2],
    'MAM' : [3, 4, 5],
}
CMAP_PRECIP = 'YlGnBu'
CMAP_ANOM   = 'RdBu'

DATA_PATH   = '/content/drive/MyDrive/DataTA/SumatBag-Selatan_1983-2024.nc'
NINO34_PATH = '/content/drive/MyDrive/DataTA/nino34_monthly.csv'   # kolom: year, month, index
DMI_PATH    = '/content/drive/MyDrive/DataTA/dmi_monthly.csv'      # kolom: year, month, index

from google.colab import drive
drive.mount('/content/drive')


# ==============================================================================
# TAHAP 1: MEMUAT DATASET & MEMOTONG DOMAIN
# ==============================================================================

ds  = xr.open_dataset(DATA_PATH)
print("Dataset asli:")
print(ds, "\n")

# Deteksi nama variabel presipitasi & dimensi lat/lon secara otomatis, lalu
# potong dataset sesuai domain penelitian.
precip_var = [v for v in ds.data_vars if 'precip' in v.lower() or 'rain' in v.lower() or 'prcp' in v.lower()][0]
lat_name   = [d for d in ds.dims if 'lat' in d.lower()][0]
lon_name   = [d for d in ds.dims if 'lon' in d.lower()][0]

ds = ds.sel(
    {lat_name: slice(LAT_MIN, LAT_MAX),
     lon_name: slice(LON_MIN, LON_MAX)}
)

precip = ds[precip_var]   # DataArray utama
lat    = precip[lat_name].values
lon    = precip[lon_name].values
n_lat, n_lon = len(lat), len(lon)
M = n_lat * n_lon          # jumlah titik grid spasial

print(f"Variabel presipitasi : '{precip_var}'")
print(f"Dimensi lat × lon   : {n_lat} × {n_lon} = {M} titik grid")
print(f"Periode waktu        : {str(precip.time.values[0])[:7]} – {str(precip.time.values[-1])[:7]}")


# ==============================================================================
# PLOT 1: PETA DOMAIN PENELITIAN
# ==============================================================================

fig, ax = plt.subplots(figsize=(7, 5), subplot_kw={'projection': ccrs.PlateCarree()})
ax.set_extent([LON_MIN - 1, LON_MAX + 1, LAT_MIN - 1, LAT_MAX + 1], crs=ccrs.PlateCarree())
ax.add_feature(cfeature.LAND,      facecolor='lightgray', zorder=0)
ax.add_feature(cfeature.OCEAN,     facecolor='lightblue', zorder=0)
ax.add_feature(cfeature.COASTLINE, linewidth=0.8)
ax.add_feature(cfeature.BORDERS,   linewidth=0.5, linestyle=':')

# Kotak batas domain penelitian
rect = mpatches.Rectangle(
    (LON_MIN, LAT_MIN), LON_MAX - LON_MIN, LAT_MAX - LAT_MIN,
    linewidth=2, edgecolor='red', facecolor='none',
    transform=ccrs.PlateCarree(), zorder=5
)
ax.add_patch(rect)

gl = ax.gridlines(draw_labels=True, linewidth=0.5, color='gray', alpha=0.7)
gl.top_labels = gl.right_labels = False
ax.set_title('Domain Penelitian: Sumatera Bagian Selatan', fontweight='bold')
plt.tight_layout()
plt.savefig('fig_00_domain.png')
plt.show()


# ==============================================================================
# PLOT 2: KLIMATOLOGI BULANAN RATA-RATA SPASIAL
# ==============================================================================

klimatologi_bulanan = precip.groupby('time.month').mean(dim='time')      # (12, lat, lon)
klim_spasial        = klimatologi_bulanan.mean(dim=[lat_name, lon_name]) # (12,)

bulan_label = ['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des']

fig, ax = plt.subplots(figsize=(9, 4))
ax.bar(np.arange(1, 13), klim_spasial.values, color='steelblue', edgecolor='white', linewidth=0.6)
ax.set_xticks(np.arange(1, 13))
ax.set_xticklabels(bulan_label)
ax.set_xlabel('Bulan')
ax.set_ylabel('Curah Hujan (mm/bulan)')
ax.set_title('Klimatologi Bulanan Rata-rata Spasial – Sumatera Bagian Selatan (1983–2024)',
             fontweight='bold')
ax.grid(axis='y', alpha=0.4)
plt.tight_layout()
plt.savefig('fig_01_klimatologi_bulanan.png')
plt.show()


# ==============================================================================
# PLOT 3: PETA KLIMATOLOGI PER MUSIM
# ==============================================================================

fig, axes = plt.subplots(1, 4, figsize=(16, 4), subplot_kw={'projection': ccrs.PlateCarree()})

# Loop menggambar peta klimatologi musiman (rata-rata 3 bulan) untuk tiap musim
for ax, (season, months) in zip(axes, SEASON_MONTHS.items()):
    klim_season = klimatologi_bulanan.sel(month=months).mean(dim='month')
    vmax_s = float(klim_season.quantile(0.98))
    im = klim_season.plot(
        ax=ax, transform=ccrs.PlateCarree(),
        cmap=CMAP_PRECIP, vmin=0, vmax=vmax_s,
        add_colorbar=False
    )
    ax.set_extent([LON_MIN, LON_MAX, LAT_MIN, LAT_MAX])
    ax.coastlines(resolution='10m', linewidth=0.6)
    ax.add_feature(cfeature.BORDERS, linewidth=0.4, linestyle=':')
    ax.set_title(season, fontweight='bold')
    plt.colorbar(im, ax=ax, orientation='horizontal', pad=0.05, label='mm/bulan', shrink=0.9)

fig.suptitle('Klimatologi Musiman Curah Hujan (1983–2024)', fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('fig_02_klimatologi_musiman.png', bbox_inches='tight')
plt.show()


# ==============================================================================
# TAHAP 2: PERHITUNGAN ANOMALI CURAH HUJAN (Persamaan 3.6)
# ==============================================================================

anomali = precip.groupby('time.month') - klimatologi_bulanan
anomali.name = 'anomali_precip'
anomali.attrs['units'] = 'mm/bulan'
anomali.attrs['long_name'] = 'Anomali Curah Hujan Bulanan'

print(f"Anomali — shape  : {anomali.shape}")
print(f"         nilai   : [{float(anomali.min()):.2f}, {float(anomali.max()):.2f}] mm/bulan")

# Verifikasi: rata-rata anomali setiap bulan harus ~0
anomali_mean_check = anomali.groupby('time.month').mean(dim='time').mean(dim=[lat_name, lon_name])
print(f"         cek mean/bulan (harus ~0): min={float(anomali_mean_check.min()):.4f}, "
      f"max={float(anomali_mean_check.max()):.4f}")


# ==============================================================================
# TAHAP 3: RATA-RATA MUSIMAN ANOMALI (Persamaan 3.7)
# ==============================================================================

def hitung_rata_musiman(da, lat_dim=lat_name, lon_dim=lon_name):
    """
    Mengelompokkan anomali bulanan menjadi rata-rata musiman per tahun.

    Mengembalikan dict {season: DataArray(year, lat, lon)}
    dengan DJF merujuk pada Desember tahun-0 + Jan,Feb tahun-1,
    diindeks pada tahun-0 sebagai tahun ENSO.
    """
    seasonal = {}
    years = np.unique(da.time.dt.year.values)

    for season, months in SEASON_MONTHS.items():
        maps = []
        year_list = []
        for y in years:
            if season == 'DJF':
                # Des tahun-y, Jan+Feb tahun-y+1
                try:
                    des = da.sel(time=(da.time.dt.year == y)   & (da.time.dt.month == 12))
                    jan = da.sel(time=(da.time.dt.year == y+1) & (da.time.dt.month == 1))
                    feb = da.sel(time=(da.time.dt.year == y+1) & (da.time.dt.month == 2))
                    if des.time.size == 0 or jan.time.size == 0 or feb.time.size == 0:
                        continue
                    mean_3bln = xr.concat([des, jan, feb], dim='time').mean(dim='time')
                except Exception:
                    continue
            else:
                sel = da.sel(time=da.time.dt.month.isin(months) & (da.time.dt.year == y))
                if sel.time.size < 3:
                    continue
                mean_3bln = sel.mean(dim='time')

            maps.append(mean_3bln.values)
            year_list.append(y)

        arr = np.array(maps)  # (N_year, n_lat, n_lon)
        seasonal[season] = xr.DataArray(
            arr,
            dims=['year', lat_dim, lon_dim],
            coords={'year': year_list, lat_dim: da[lat_dim].values, lon_dim: da[lon_dim].values},
            attrs={'units': 'mm/bulan', 'long_name': f'Anomali rata-rata {season}'}
        )

    return seasonal

seasonal_anom = hitung_rata_musiman(anomali)

for s, da_s in seasonal_anom.items():
    print(f"  {s}: {da_s.shape},  tahun {int(da_s.year[0])}–{int(da_s.year[-1])}")


# ==============================================================================
# TAHAP 4: KONSTRUKSI MATRIKS DATA S-EOF (Persamaan 3.8 – 3.9)
# ==============================================================================

years_jja  = set(seasonal_anom['JJA'].year.values.tolist())
years_son  = set(seasonal_anom['SON'].year.values.tolist())
years_djf  = set(seasonal_anom['DJF'].year.values.tolist())
years_mam  = set(seasonal_anom['MAM'].year.values.tolist())

# Tahun y valid jika JJA(y), SON(y), DJF(y), dan MAM(y+1) semuanya tersedia
years_valid_raw = sorted(
    y for y in years_jja & years_son & years_djf
    if (y + 1) in years_mam
)
years_valid = np.array(years_valid_raw)
N = len(years_valid)
print(f"Tahun siklus lengkap: {years_valid[0]}–{years_valid[-1]}  (N = {N} tahun)")

# Susun vektor tahunan x_y (gabungan JJA-SON-DJF-MAM) menjadi matriks X (4M × N)
blocks = []
for y in years_valid:
    jja = seasonal_anom['JJA'].sel(year=y).values.reshape(-1)
    son = seasonal_anom['SON'].sel(year=y).values.reshape(-1)
    djf = seasonal_anom['DJF'].sel(year=y).values.reshape(-1)
    mam = seasonal_anom['MAM'].sel(year=y + 1).values.reshape(-1)
    blocks.append(np.concatenate([jja, son, djf, mam]))

X = np.array(blocks).T          # (4M, N)

print(f"Matriks X (S-EOF)   : {X.shape}  [4M={4*M}, N={N}]")
print(f"  Nilai: [{np.nanmin(X):.2f}, {np.nanmax(X):.2f}] mm/bulan")

# Masking NaN: buang grid point yang NaN di semua tahun
mask_spatial = ~np.isnan(X).any(axis=1)   # (4M,) — True jika valid di seluruh tahun
X_clean      = X[mask_spatial, :]
mask_year    = ~np.isnan(X_clean).any(axis=0)
X_clean      = X_clean[:, mask_year]
years_valid  = years_valid[mask_year]
N            = X_clean.shape[1]

print(f"\nSetelah masking NaN :")
print(f"  Grid valid  : {mask_spatial.sum()} dari {4*M} (dibuang: {(~mask_spatial).sum()})")
print(f"  Tahun valid : {N} ({years_valid[0]}–{years_valid[-1]})")
print(f"  X_clean     : {X_clean.shape}")


# ==============================================================================
# TAHAP 5: DEKOMPOSISI S-EOF (Persamaan 3.10 – 3.12)
# ==============================================================================

pca = PCA(n_components=N_MODES, svd_solver='full')
pca.fit(X_clean.T)              # sklearn: baris=tahun, kolom=spasial-musiman

eigenvalues    = pca.explained_variance_             # λ_k  (mm²/bulan²)
var_frac       = pca.explained_variance_ratio_ * 100 # VE_k (%)
var_cum        = np.cumsum(var_frac)

print("Kontribusi Varians Mode S-EOF:")
print(f"  {'Mode':>4}  {'λ_k (mm²/bln²)':>18}  {'VE_k (%)':>10}  {'Kum. (%)':>10}")
for k in range(N_MODES):
    print(f"  {k+1:>4}  {eigenvalues[k]:>18.4f}  {var_frac[k]:>10.2f}  {var_cum[k]:>10.2f}")

# Eigenvector (pola spasial S-EOF); konvensi tanda: arah positif = mean positif dominan
E = pca.components_.T       # (4M_valid, N_MODES)
for k in range(N_MODES):
    if E[:, k].mean() < 0:
        E[:, k] *= -1

# Principal Component PC_k(y) = E_k^T x_y (mm/bulan), via proyeksi langsung
PC_raw = X_clean.T @ E      # (N, N_MODES)

# Verifikasi: bandingkan dengan sklearn transform (harus identik setelah koreksi tanda)
PC_sk = pca.transform(X_clean.T)
for k in range(N_MODES):
    if np.sign(PC_raw[:, k].mean()) != np.sign(PC_sk[:, k].mean()):
        PC_sk[:, k] *= -1

PC = PC_raw        # (N, N_MODES) satuan: mm/bulan — dipakai karena transparan secara matematis

print(f"\nPC shape: {PC.shape}  (N_tahun × N_modes)  satuan: mm/bulan")


# ==============================================================================
# TAHAP 6: PARTISI POLA SPASIAL MUSIMAN (Persamaan 3.13)
# ==============================================================================

PC_std = PC.std(axis=0)     # (N_MODES,) mm/bulan

EOF_maps  = np.full((N_MODES, 4, n_lat, n_lon), np.nan)
SEOF_maps = np.full((N_MODES, 4, n_lat, n_lon), np.nan)

# Kembalikan tiap mode ke grid penuh (termasuk titik yang dimasking), lalu
# pecah menjadi 4 peta musiman: EOF (eigenvector) dan SEOF (satuan fisik).
for k in range(N_MODES):
    full_vector = np.full(4 * M, np.nan)
    full_vector[mask_spatial] = E[:, k]

    for s_idx in range(4):
        seg = full_vector[s_idx * M : (s_idx + 1) * M]
        EOF_maps[k, s_idx]  = seg.reshape(n_lat, n_lon)
        SEOF_maps[k, s_idx] = seg.reshape(n_lat, n_lon) * PC_std[k]

# Verifikasi MAM: pastikan tidak semua NaN
for k in range(N_MODES):
    n_nan = np.isnan(SEOF_maps[k, 3]).sum()
    n_tot = SEOF_maps[k, 3].size
    if n_nan == n_tot:
        print(f"  PERINGATAN: Mode {k+1} MAM seluruhnya NaN — periksa mask_spatial!")

print("Pola S-EOF berhasil dipartisi:")
print(f"  EOF_maps  (eigenvector)  : {EOF_maps.shape}   tak berdimensi")
print(f"  SEOF_maps (mm/bulan)     : {SEOF_maps.shape}  = eigenvec × std(PC)")

# Kemas seluruh hasil S-EOF ke satu xarray Dataset lalu simpan ke NetCDF
ds_seof = xr.Dataset(
    data_vars={
        'EOF_map': (
            ['mode', 'season', lat_name, lon_name], EOF_maps,
            {'long_name'  : 'Eigenvector S-EOF (ternormalisasi)',
             'units'      : '1',
             'description': 'E_k,s — pola spasial ternormalisasi; L2-norm = 1'}
        ),
        'SEOF_map': (
            ['mode', 'season', lat_name, lon_name], SEOF_maps,
            {'long_name'  : 'Pola Spasial S-EOF (satuan fisik)',
             'units'      : 'mm/bulan',
             'description': 'E_k,s * std(PC_k) — anomali curah hujan per 1-std PC'}
        ),
        'PC': (
            ['year', 'mode'], PC,
            {'long_name': 'Komponen Utama S-EOF',
             'units'    : 'mm/bulan',
             'description': 'PC_k(y) = E_k^T x_y'}
        ),
        'eigenvalue': (
            ['mode'], eigenvalues,
            {'long_name': 'Eigenvalue S-EOF',
             'units'    : 'mm^2/bulan^2'}
        ),
        'var_percent': (
            ['mode'], var_frac,
            {'long_name': 'Kontribusi Varians per Mode',
             'units'    : '%'}
        ),
        'var_cumulative': (
            ['mode'], var_cum,
            {'long_name': 'Kontribusi Varians Kumulatif',
             'units'    : '%'}
        ),
        'PC_std': (
            ['mode'], PC_std,
            {'long_name': 'Standar Deviasi PC',
             'units'    : 'mm/bulan'}
        ),
    },
    coords={
        'mode'   : np.arange(1, N_MODES + 1),
        'season' : SEASONS,
        lat_name : lat,
        lon_name : lon,
        'year'   : years_valid,
    },
    attrs={
        'title'       : 'S-EOF Analysis — Sumatera Bagian Selatan',
        'method'      : 'Season-reliant EOF (Wang & An, 2005)',
        'reference'   : 'Hou et al. (2016), Remote Sensing, vol. 8, no. 833',
        'data_source' : 'CHIRPS v2.0',
        'domain'      : f'{LON_MIN}°E–{LON_MAX}°E, {LAT_MIN}°S–{LAT_MAX}°S',
        'period'      : f'{years_valid[0]}–{years_valid[-1]}',
        'season_order': 'JJA(0) → SON(0) → DJF(0/1) → MAM(1)',
        'n_modes'     : N_MODES,
    }
)

print(ds_seof)

output_nc = '/content/drive/MyDrive/DataTA/SEOF_hasilFitSklearn_SumatBagSelatan.nc'
ds_seof.to_netcdf(output_nc)
print(f"\nDataset tersimpan: {output_nc}")


# ==============================================================================
# PLOT 4: SCREE PLOT (KONTRIBUSI VARIANS)
# ==============================================================================

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

ax = axes[0]
ax.bar(np.arange(1, N_MODES + 1), var_frac, color='steelblue', edgecolor='white', linewidth=0.7)
ax.plot(np.arange(1, N_MODES + 1), var_frac, 'o-', color='navy', markersize=5, linewidth=1.5)
ax.set_xlabel('Mode S-EOF ke-')
ax.set_ylabel('Kontribusi Varians (%)')
ax.set_title('Scree Plot — Kontribusi Varians', fontweight='bold')
ax.set_xticks(np.arange(1, N_MODES + 1))
ax.grid(axis='y', alpha=0.4)

ax = axes[1]
ax.plot(np.arange(1, N_MODES + 1), var_cum, 's-', color='darkred', markersize=5, linewidth=1.5)
ax.axhline(y=80, color='gray', linestyle='--', linewidth=1, label='80%')
ax.axhline(y=90, color='gray', linestyle=':',  linewidth=1, label='90%')
ax.set_xlabel('Mode S-EOF ke-')
ax.set_ylabel('Varians Kumulatif (%)')
ax.set_title('Varians Kumulatif', fontweight='bold')
ax.set_xticks(np.arange(1, N_MODES + 1))
ax.set_ylim(0, 105)
ax.legend(fontsize=9)
ax.grid(axis='y', alpha=0.4)

# Anotasi nilai varians pada mode-mode utama (LEAD_MODES)
for k in LEAD_MODES:
    axes[0].annotate(f'{var_frac[k-1]:.1f}%', xy=(k, var_frac[k-1]),
                     xytext=(0, 6), textcoords='offset points',
                     ha='center', fontsize=9, color='navy')
    axes[1].annotate(f'{var_cum[k-1]:.1f}%', xy=(k, var_cum[k-1]),
                     xytext=(0, 6), textcoords='offset points',
                     ha='center', fontsize=9, color='darkred')

plt.suptitle('S-EOF — Sumatera Bagian Selatan (1983–2024)', fontweight='bold')
plt.tight_layout()
plt.savefig('fig_03_scree_plot.png')
plt.show()


# ==============================================================================
# HELPER PETA: DEKORASI STANDAR (dipakai oleh seluruh plot spasial di bawah)
# ==============================================================================

def _map_extent_and_decor(ax):
    """Helper: set batas peta dan dekorasi standar."""
    ax.set_extent([LON_MIN, LON_MAX, LAT_MIN, LAT_MAX], crs=ccrs.PlateCarree())
    ax.coastlines(resolution='10m', linewidth=0.7)
    ax.add_feature(cfeature.BORDERS, linewidth=0.4, linestyle=':')
    gl = ax.gridlines(draw_labels=True, linewidth=0.3, color='gray', alpha=0.6,
                      x_inline=False, y_inline=False)
    gl.top_labels = gl.right_labels = False
    gl.xlocator = mticker.MultipleLocator(2)
    gl.ylocator = mticker.MultipleLocator(1)


# ==============================================================================
# PLOT 5: POLA SPASIAL S-EOF PER MODE (peta 4 musim + deret waktu PC standar)
# ==============================================================================

for mode_k in LEAD_MODES:
    k = mode_k - 1   # indeks 0-based
    data_k = ds_seof['SEOF_map'].sel(mode=mode_k)  # (season, lat, lon)

    # Simetriskan colorbar: ambil persentil 95 dari nilai absolut keempat musim
    vabs = float(np.nanpercentile(np.abs(data_k.values), 95))
    norm = TwoSlopeNorm(vmin=-vabs, vcenter=0, vmax=vabs)

    fig = plt.figure(figsize=(13, 9))
    gs_main = gridspec.GridSpec(3, 2, figure=fig, height_ratios=[1, 1, 0.55],
                                hspace=0.38, wspace=0.15)
    map_axes = [
        fig.add_subplot(gs_main[0, 0], projection=ccrs.PlateCarree()),
        fig.add_subplot(gs_main[0, 1], projection=ccrs.PlateCarree()),
        fig.add_subplot(gs_main[1, 0], projection=ccrs.PlateCarree()),
        fig.add_subplot(gs_main[1, 1], projection=ccrs.PlateCarree()),
    ]

    # Loop menggambar peta anomali S-EOF untuk keempat musim (JJA/SON/DJF/MAM)
    for s_idx, (ax, season) in enumerate(zip(map_axes, SEASONS)):
        smap = data_k.sel(season=season)
        im = ax.pcolormesh(lon, lat, smap.values, norm=norm, cmap=CMAP_ANOM,
                           transform=ccrs.PlateCarree())
        _map_extent_and_decor(ax)
        ax.set_title(f'{season}', fontweight='bold', fontsize=12)

    # Colorbar tunggal mewakili keempat peta
    cbar_ax = fig.add_axes([0.92, 0.42, 0.018, 0.46])
    cb = fig.colorbar(im, cax=cbar_ax, extend='both')
    cb.set_label('Anomali Curah Hujan (mm/bulan)\n[per 1-std PC]', fontsize=10)

    # Panel deret waktu PC, distandardisasi (z-score) langsung saat plot
    ax_pc = fig.add_subplot(gs_main[2, :])
    pc_raw = ds_seof['PC'].sel(mode=mode_k).values   # (N,)
    pc_mean = np.mean(pc_raw)
    pc_std = np.std(pc_raw, ddof=1)
    pc_series = (pc_raw - pc_mean) / pc_std           # z-score

    colors_bar = ['#4575b4' if v > 0 else '#d73027' for v in pc_series]
    ax_pc.bar(years_valid, pc_series, color=colors_bar, width=0.7, alpha=0.85)
    ax_pc.axhline(0,  color='k', linewidth=0.8)
    ax_pc.axhline( 1, color='b', linewidth=1.2, linestyle='--', alpha=0.7, label='+1 std')
    ax_pc.axhline(-1, color='r', linewidth=1.2, linestyle='--', alpha=0.7, label='−1 std')
    ax_pc.set_xlabel('Tahun')
    ax_pc.set_ylabel('PC (standar)')
    ax_pc.set_title(f'Deret Waktu PC Mode-{mode_k}', fontweight='bold')
    ax_pc.legend(fontsize=9, loc='upper right')
    ax_pc.set_xlim(years_valid[0] - 0.5, years_valid[-1] + 0.5)
    ax_pc.set_ylim(-2, 2)
    ax_pc.grid(axis='y', alpha=0.35)

    fig.suptitle(
        f'S-EOF Mode-{mode_k}  ({var_frac[k]:.1f}% varians)\n'
        f'Evolusi Musiman Anomali Curah Hujan — Sumatera Bagian Selatan',
        fontweight='bold', fontsize=13, y=0.98
    )
    plt.savefig(f'fig_04_SEOF_mode{mode_k}_pola_spasial.png', bbox_inches='tight')
    plt.show()


# ==============================================================================
# PLOT 6: DERET WAKTU PC + ENSO (NINO3.4) + IOD (DMI)
# ==============================================================================

# Baca data ENSO (NINO3.4) dan IOD (DMI) bulanan, buat kolom datetime
nino = pd.read_csv(NINO34_PATH)
dmi  = pd.read_csv(DMI_PATH)
nino['date'] = pd.to_datetime(dict(year=nino.year, month=nino.month, day=1))
dmi['date']  = pd.to_datetime(dict(year=dmi.year,  month=dmi.month,  day=1))

# Posisi batang PC di pertengahan tahun
pc_dates = pd.to_datetime([f'{yy}-07-01' for yy in years_valid])

fig, axes = plt.subplots(len(LEAD_MODES), 1, figsize=(13, 3.8 * len(LEAD_MODES)), sharex=True)
if len(LEAD_MODES) == 1:
    axes = [axes]

# Loop menggambar PC (z-score, batang) tiap mode dengan overlay NINO3.4/DMI (sumbu kanan)
for ax, mode_k in zip(axes, LEAD_MODES):
    pc_k = ds_seof['PC'].sel(mode=mode_k).values
    pc_z = (pc_k - pc_k.mean()) / pc_k.std()
    colors_bar = ['#4575b4' if v > 0 else '#d73027' for v in pc_z]

    ax.bar(pc_dates, pc_z, width=220, color=colors_bar, alpha=0.85, zorder=2)
    ax.axhline(0, color='k', linewidth=0.8)
    ax.axhline(1, color='b', linestyle='--', linewidth=1, alpha=0.6)
    ax.axhline(-1, color='r', linestyle='--', linewidth=1, alpha=0.6)

    ax2 = ax.twinx()
    ax2.plot(nino['date'], nino['nino34'], color='darkorange', linewidth=1.0,
             alpha=0.85, label='NINO3.4', zorder=3)
    ax2.plot(dmi['date'], dmi['dmi'], color='forestgreen', linewidth=1.0,
             alpha=0.85, label='DMI', zorder=3)
    ax2.set_ylabel('Indeks NINO 3.4 / DMI')

    vmax = max(np.nanmax(np.abs(nino['nino34'])), np.nanmax(np.abs(dmi['dmi'])))
    ax2.set_ylim(-vmax*1.1, vmax*1.1)

    ax.set_ylabel('PC (z-score)')
    ax.set_title(f'PC Mode-{mode_k} (VE = {var_frac[mode_k-1]:.1f}%)', fontweight='bold')
    ax.grid(axis='y', alpha=0.35)

    h1, l1 = ax2.get_legend_handles_labels()
    ax2.legend(h1, l1, loc='upper right', frameon=True, fontsize=9)

axes[-1].set_xlabel('Tahun')
axes[-1].xaxis.set_major_locator(mdates.YearLocator(5))
axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
axes[-1].set_xlim(pd.Timestamp('1983-01-01'), pd.Timestamp('2024-12-31'))

fig.suptitle(
    'Deret Waktu Komponen Utama S-EOF (z-score)\n'
    'dengan Variabilitas ENSO (NINO3.4) dan IOD (DMI)\n'
    'Sumatera Bagian Selatan (1983–2024)',
    fontsize=13, fontweight='bold'
)
plt.tight_layout()
plt.savefig('fig_05_PC_timeseries.png', dpi=600, bbox_inches='tight')
plt.show()


# ==============================================================================
# TAHAP 7: FUNGSI ANALISIS KORELASI LEAD-LAG (Persamaan 3.15 – 3.16)
# ==============================================================================

def muat_indeks(path, kolom_nilai, sep=','):
    """Muat indeks iklim bulanan dari CSV dan kembalikan xarray DataArray."""
    df = pd.read_csv(path, sep=sep)
    df['time'] = pd.to_datetime(df[['year', 'month']].assign(day=1))
    df = df.sort_values('time').reset_index(drop=True)
    da = xr.DataArray(
        df[kolom_nilai].values,
        dims=['time'],
        coords={'time': df['time'].values}
    )
    return da

def rata_musiman_indeks(da_monthly):
    """
    Rata-ratakan indeks bulanan ke musiman sesuai Persamaan 3.15.
    Mengembalikan dict {season: DataArray(year,)}
    """
    seasonal_idx = {}
    years = np.unique(da_monthly.time.dt.year.values)
    for season, months in SEASON_MONTHS.items():
        vals, yrs = [], []
        for y in years:
            if season == 'DJF':
                des = da_monthly.sel(time=(da_monthly.time.dt.year == y) &
                                        (da_monthly.time.dt.month == 12))
                jan = da_monthly.sel(time=(da_monthly.time.dt.year == y+1) &
                                        (da_monthly.time.dt.month == 1))
                feb = da_monthly.sel(time=(da_monthly.time.dt.year == y+1) &
                                        (da_monthly.time.dt.month == 2))
                if des.size == 0 or jan.size == 0 or feb.size == 0:
                    continue
                val = float(xr.concat([des, jan, feb], dim='time').mean())
            else:
                sel = da_monthly.sel(time=da_monthly.time.dt.month.isin(months) &
                                         (da_monthly.time.dt.year == y))
                if sel.size < 3:
                    continue
                val = float(sel.mean())
            vals.append(val)
            yrs.append(y)
        seasonal_idx[season] = xr.DataArray(vals, dims=['year'], coords={'year': yrs})
    return seasonal_idx

def korelasi_leadlag(pc_series, idx_seasonal, years_pc, tau_range=(-1, 1)):
    """
    Hitung korelasi lead-lag r_{k,s}(τ) sesuai Persamaan 3.16.

    Parameter
    ----------
    pc_series   : array (N,) — PC tahunan mode-k
    idx_seasonal: dict {season: array (N_year,)} — indeks iklim musiman
    years_pc    : array (N,) — tahun yang bersesuaian dengan pc_series
    tau_range   : (tau_min, tau_max) dalam satuan tahun

    Mengembalikan
    -------------
    r_matrix : dict {season: array (n_tau,)} — koefisien korelasi
    tau_vals : array (n_tau,) — nilai lag τ
    """
    tau_vals = np.arange(tau_range[0], tau_range[1] + 1)
    r_matrix = {s: np.full(len(tau_vals), np.nan) for s in SEASONS}
    pc_mean = pc_series.mean()

    for t_idx, tau in enumerate(tau_vals):
        for season in SEASONS:
            idx_da = idx_seasonal[season]
            idx_yrs = idx_da.year.values

            # Sesuaikan tahun: I_{s, y+tau}, lalu ambil irisan tahun yang valid
            years_shifted = years_pc + tau
            common = np.intersect1d(years_shifted, idx_yrs)
            if len(common) < 5:   # minimal 5 pasangan untuk korelasi bermakna
                continue

            mask_pc  = np.isin(years_shifted, common)
            mask_idx = np.isin(idx_yrs, common)
            pc_sub  = pc_series[mask_pc]
            idx_sub = idx_da.values[mask_idx]
            idx_mean = idx_sub.mean()

            num  = np.sum((pc_sub - pc_mean) * (idx_sub - idx_mean))
            den  = np.sqrt(np.sum((pc_sub - pc_mean)**2) * np.sum((idx_sub - idx_mean)**2))
            if den == 0:
                continue
            r_matrix[season][t_idx] = num / den

    return r_matrix, tau_vals


# ==============================================================================
# PLOT 7: HEATMAP KORELASI LEAD-LAG PER MODE & INDEKS IKLIM
# ==============================================================================

def plot_leadlag(r_matrices, tau_vals, mode_k, idx_name, alpha=0.05, N_eff=None):
    """
    Tampilkan diagram korelasi lead-lag 2D:
      sumbu-x = musim (JJA, SON, DJF, MAM)
      sumbu-y = lag τ (tahun)
    dengan hatching pada area yang melewati batas signifikansi two-tailed.
    """
    n_eff  = N_eff if N_eff else len(years_valid)
    t_crit = stats.t.ppf(1 - alpha / 2, df=n_eff - 2)
    r_crit = t_crit / np.sqrt(t_crit**2 + n_eff - 2)

    R_mat = np.array([r_matrices[s] for s in SEASONS]).T   # (n_tau, 4)

    fig, ax = plt.subplots(figsize=(7, 5))
    im = ax.pcolormesh(np.arange(4), tau_vals, R_mat, cmap='RdBu', vmin=-1, vmax=1,
                       shading='nearest')

    sig = np.abs(R_mat) >= r_crit
    for t_i, tau in enumerate(tau_vals):
        for s_i in range(4):
            if sig[t_i, s_i]:
                ax.add_patch(plt.Rectangle((s_i - 0.5, tau - 0.5), 1, 1,
                                           fill=False, hatch='...', edgecolor='k',
                                           linewidth=0, alpha=0.6))

    ax.set_xticks(np.arange(4)); ax.set_xticklabels(SEASONS)
    ax.set_yticks(tau_vals); ax.set_yticklabels([f'τ={t:+d}' for t in tau_vals])
    ax.set_xlabel('Musim Indeks Iklim')
    ax.set_ylabel('Lag τ (tahun)\n[ τ>0: indeks mendahului PC ]')
    ax.set_title(
        f'Korelasi Lead-Lag: PC Mode-{mode_k} vs {idx_name}\n'
        f'(titik = signifikan p<{alpha:.2f}, r_crit={r_crit:.2f})',
        fontweight='bold'
    )
    cb = plt.colorbar(im, ax=ax, shrink=0.85)
    cb.set_label('Koefisien Korelasi (r)', fontsize=10)
    plt.tight_layout()
    plt.savefig(f'fig_06_leadlag_mode{mode_k}_{idx_name}.png')
    plt.show()

nino34_monthly = muat_indeks(NINO34_PATH, kolom_nilai='nino34')
dmi_monthly    = muat_indeks(DMI_PATH,    kolom_nilai='dmi')
nino34_seas = rata_musiman_indeks(nino34_monthly)
dmi_seas    = rata_musiman_indeks(dmi_monthly)

# Loop menggambar heatmap lead-lag untuk tiap mode utama terhadap Niño3.4 & DMI
for mode_k in LEAD_MODES:
    pc_k = ds_seof['PC'].sel(mode=mode_k).values
    r_nino34, tau_vals = korelasi_leadlag(pc_k, nino34_seas, years_valid)
    plot_leadlag(r_nino34, tau_vals, mode_k, 'Niño3.4')
    r_dmi, tau_vals = korelasi_leadlag(pc_k, dmi_seas, years_valid)
    plot_leadlag(r_dmi,   tau_vals, mode_k, 'DMI (IOD)')


# ==============================================================================
# PLOT 8: KORELASI LEAD-LAG GABUNGAN (Niño3.4 vs DMI, seluruh mode & musim)
# ==============================================================================

def plot_korelasi_gabungan(dict_r_nino, dict_r_dmi, tau_vals, N_eff):
    """
    Menampilkan grafik garis korelasi lead-lag untuk Niño3.4 dan DMI dalam satu
    figure, dengan satu sub-panel per mode dan sumbu-x kontinu (musim x lag).
    """
    modes = list(dict_r_nino.keys())

    # Aproksimasi t kritis alpha=0.05 (two-tailed, valid untuk sampel menengah-besar)
    alpha = 0.05
    t_crit = 1.96
    r_crit = t_crit / np.sqrt(t_crit**2 + N_eff - 2)

    fig, axes = plt.subplots(len(modes), 1, figsize=(10, 4.5 * len(modes)), sharex=True)
    if len(modes) == 1:
        axes = [axes]

    n_tau = len(tau_vals)
    x_ticks = np.arange(n_tau * 4)
    x_labels = SEASONS * n_tau

    # Loop tiap mode: flatten korelasi musiman ke sumbu-x kontinu, lalu plot garis
    for idx, mode in enumerate(modes):
        ax = axes[idx]
        y_nino, y_dmi = [], []
        for t_idx in range(n_tau):
            for s in SEASONS:
                y_nino.append(dict_r_nino[mode][s][t_idx])
                y_dmi.append(dict_r_dmi[mode][s][t_idx])

        ax.plot(x_ticks, y_nino, marker='*', markersize=6, color='#d73027',
               linewidth=2, label='Niño3.4')
        ax.plot(x_ticks, y_dmi, marker='*', markersize=6, color='#4575b4',
               linewidth=2, label='DMI (IOD)')

        # Garis bantu horizontal & batas signifikansi
        for y_line in np.arange(-0.8, 0.9, 0.2):
            ax.axhline(y_line, color='grey', linestyle='--', linewidth=0.7, alpha=0.5)
        ax.axhline(r_crit,  color='#968b5a', linestyle='-.', linewidth=1.2, alpha=0.7)
        ax.axhline(-r_crit, color='#968b5a', linestyle='-.', linewidth=1.2, alpha=0.7)

        ax.set_ylim(-0.9, 0.9)
        ax.set_yticks(np.arange(-0.8, 0.9, 0.2))

        # Garis pemisah antar-lag & label Y(-1)/Y(0)/dst di bawah tiap blok musim
        for i in range(1, n_tau):
            ax.axvline(i * 4 - 0.5, color='k', linewidth=0.8)
        for i, tau in enumerate(tau_vals):
            ax.text(i * 4 + 1.5, -0.75, f'Y({tau:+d})', ha='center', va='center',
                   fontsize=12, fontweight='bold')

        panel_label = chr(ord('a') + idx)
        ax.set_title(f'({panel_label}) korelasi (mode {mode}, Niño3.4 & DMI)', fontsize=11)
        ax.tick_params(axis='x', which='both', bottom=True, top=False, direction='in')
        if idx == 0:
            ax.legend(loc='upper right', framealpha=0.9, fontsize=9)

    axes[-1].set_xticks(x_ticks)
    axes[-1].set_xticklabels(x_labels, fontsize=10)

    fig.suptitle(
        'Analisis Korelasi Lead-Lag Komponen Utama S-EOF\n'
        'Sumatera Bagian Selatan (1983–2024)',
        fontweight='bold', fontsize=14, y=0.96
    )
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    plt.savefig('fig_06_leadlag_gabungan.png', dpi=300, bbox_inches='tight')
    plt.show()

# Hitung korelasi lead-lag tiap mode utama, lalu tampilkan grafik gabungan
korelasi_nino_all = {}
korelasi_dmi_all = {}
for mode_k in LEAD_MODES:
    pc_k = ds_seof['PC'].sel(mode=mode_k).values
    r_nino34, tau_vals = korelasi_leadlag(pc_k, nino34_seas, years_valid)
    r_dmi, _ = korelasi_leadlag(pc_k, dmi_seas, years_valid)
    korelasi_nino_all[mode_k] = r_nino34
    korelasi_dmi_all[mode_k] = r_dmi

plot_korelasi_gabungan(korelasi_nino_all, korelasi_dmi_all, tau_vals, N_eff=len(years_valid))